apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta2.custom.metrics.k8s.io
  labels:
    app: activescale
    workload: metrics-adapter
spec:
  group: custom.metrics.k8s.io
  version: v1beta2
  service:
    name: activescale
    namespace: ns-observability
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 200
